# Generated by Django 4.1.1 on 2022-09-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='profile_img',
            new_name='project_img',
        ),
    ]
